apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: jenne09/challenge-e06-back:v2
        name: challenge-back
        ports:
          - containerPort: 5000
        resources: 
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            cpu: 80m
            memory: 32Mi
status: {}